version: '3.8'

services:
  web:
    build: .
    container_name: netinsight_web
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - NETINSIGHT_DEMO_MODE=True
      - NETINSIGHT_LINK_CAPACITY=100000000.0
      - NETINSIGHT_REFRESH_INTERVAL=2000
    volumes:
      - netinsight_db:/app/netinsight/database
    restart: unless-stopped

volumes:
  netinsight_db:
