# Generated by Django 5.2.16 on 2026-07-18 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(db_index=True, max_length=17, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_type', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_recv', models.BigIntegerField(default=0)),
                ('active_connections', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MetricRecord',
            fields=[
                ('timestamp', models.FloatField(db_index=True, primary_key=True, serialize=False)),
                ('throughput', models.FloatField(default=0.0)),
                ('packet_rate', models.FloatField(default=0.0)),
                ('bandwidth_util', models.FloatField(default=0.0)),
                ('latency', models.FloatField(default=0.0)),
                ('packet_loss', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='StateHistory',
            fields=[
                ('timestamp', models.FloatField(db_index=True, primary_key=True, serialize=False)),
                ('network_state', models.CharField(max_length=50)),
                ('bandwidth_utilization', models.FloatField(default=0.0)),
                ('packet_loss', models.FloatField(default=0.0)),
                ('latency', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth_threshold', models.FloatField(default=0.75)),
                ('loss_threshold', models.FloatField(default=0.05)),
                ('latency_threshold', models.FloatField(default=0.15)),
                ('hmm_thresholds', models.JSONField(default=dict)),
                ('lp_priorities', models.JSONField(default=list)),
                ('svm_confidence_threshold', models.FloatField(default=0.8)),
            ],
        ),
        migrations.CreateModel(
            name='FlowRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flow_key', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('packet_count', models.IntegerField(default=0)),
                ('byte_count', models.BigIntegerField(default=0)),
                ('avg_packet_size', models.FloatField(default=0.0)),
                ('protocol', models.CharField(max_length=20)),
                ('threat_label', models.CharField(default='Normal', max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='dashboard.agent')),
            ],
        ),
        migrations.CreateModel(
            name='PacketRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('ttl', models.IntegerField()),
                ('timestamp', models.FloatField(db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='dashboard.agent')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('threat_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='dashboard.agent')),
            ],
        ),
    ]
