# Generated by Django 5.2.16 on 2026-08-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowrecord',
            options={'ordering': ['-end_time']},
        ),
        migrations.AlterModelOptions(
            name='packetrecord',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='flowrecord',
            index=models.Index(fields=['agent', 'flow_key', 'end_time'], name='dashboard_f_agent_i_2c4daa_idx'),
        ),
        migrations.AddIndex(
            model_name='packetrecord',
            index=models.Index(fields=['agent', 'timestamp'], name='dashboard_p_agent_i_16d4f8_idx'),
        ),
    ]
