# Generated by Django 5.2.16 on 2026-08-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_flowrecord_options_alter_packetrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetrecord',
            name='tcp_seq',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
