# Generated by Django 5.2.16 on 2026-08-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_packetrecord_tcp_seq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateHistory',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='hmm_thresholds',
        ),
    ]
