# Generated by Django 5.2.16 on 2026-08-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_statehistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='svm_confidence_threshold',
            new_name='llm_confidence_threshold',
        ),
    ]
