# Generated by Django 5.2.16 on 2026-08-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_svm_confidence_threshold_systemsettings_llm_confidence_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threathistory',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='llm_confidence_threshold',
        ),
        migrations.DeleteModel(
            name='FlowRecord',
        ),
        migrations.DeleteModel(
            name='ThreatHistory',
        ),
    ]
