# Generated by Django 5.2.16 on 2026-09-15 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_threathistory_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='llm_confidence_threshold',
            field=models.FloatField(default=0.8),
        ),
        migrations.CreateModel(
            name='ThreatHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('threat_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='dashboard.agent')),
            ],
        ),
        migrations.CreateModel(
            name='FlowRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flow_key', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('packet_count', models.IntegerField(default=0)),
                ('byte_count', models.BigIntegerField(default=0)),
                ('avg_packet_size', models.FloatField(default=0.0)),
                ('protocol', models.CharField(max_length=20)),
                ('threat_label', models.CharField(default='Normal', max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='dashboard.agent')),
            ],
            options={
                'ordering': ['-end_time'],
                'indexes': [models.Index(fields=['agent', 'flow_key', 'end_time'], name='dashboard_f_agent_i_2c4daa_idx')],
            },
        ),
    ]
